"""Inspect an existing Dionaea pod without sending protocol traffic.

Reads image identity, listening IPv4 sockets, and aggregate SQLite metadata.
Does not expose new ports, change workloads, or read TLS private keys.
"""
import argparse
import ipaddress
import json
import subprocess
from datetime import datetime, timezone
from pathlib import Path

from check_protocol_runtime import SOCKET_CODE, get_json

EXPECTED_DIGEST = 'sha256:55150e2a9ef56e1b304129195affc0dc335ed35868dfde6de0ff1f2358d00515'
DATABASE_CODE = r'''
import json, sqlite3
db = sqlite3.connect('file:/opt/dionaea/var/lib/dionaea/dionaea.sqlite?mode=ro', uri=True)
try:
    rows = db.execute('SELECT connection_type, connection_transport, connection_protocol, local_port, COUNT(*) FROM connections GROUP BY connection_type, connection_transport, connection_protocol, local_port').fetchall()
    print(json.dumps([dict(connection_type=r[0], transport=r[1], protocol=r[2], local_port=r[3], records=r[4]) for r in rows]))
finally:
    db.close()
'''


def inspect(release, namespace, capture=get_json):
    pods = capture(['kubectl', 'get', 'pods', '-n', namespace, '-l',
                    'app.kubernetes.io/instance=' + release, '-o', 'json'])
    active = [p for p in pods['items'] if not p['metadata'].get('deletionTimestamp')]
    if len(active) != 1:
        raise ValueError('Expected one active pod for ' + release)
    pod = active[0]
    if not any(c['type'] == 'Ready' and c['status'] == 'True' for c in pod['status'].get('conditions', [])):
        raise ValueError('Pod is not Ready.')
    containers = {c['name']: c for c in pod['spec']['containers']}
    statuses = {c['name']: c for c in pod['status']['containerStatuses']}
    container = containers['dionaea']
    ip = ipaddress.IPv4Address(pod['status']['podIP'])
    prefix = ['kubectl', 'exec', '-n', namespace, pod['metadata']['name'], '-c', 'dionaea', '--', 'python3', '-c']
    sockets = capture(prefix + [SOCKET_CODE])
    accessible = {s['port'] for s in sockets if s['address_hex'] in ('00000000', ip.packed[::-1].hex().upper())}
    records = capture(prefix + [DATABASE_CODE])
    return dict(schema_version=1, inspected_at=datetime.now(timezone.utc).isoformat(),
                release=release, namespace=namespace, pod=pod['metadata']['name'], pod_ip=str(ip),
                requested_image=container['image'], image_id=statuses['dionaea'].get('imageID'),
                expected_digest=EXPECTED_DIGEST,
                requested_image_matches_pin=container['image'].endswith('@' + EXPECTED_DIGEST),
                selected_listener_candidates={name: {'port': port, 'bound_on_pod_ipv4': port in accessible}
                                              for name, port in [('http', 80), ('https', 443), ('smb', 445)]},
                sockets=sockets, database_record_groups=records,
                limitations=['Sockets belong to the shared pod network namespace, not an identified process.',
                             'A listening port does not prove TLS/SMB exchange or event logging.',
                             'No protocol traffic was generated by this inspection.'])


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--release', required=True)
    parser.add_argument('--namespace', default='honeypots')
    parser.add_argument('--output', required=True, type=Path)
    args = parser.parse_args()
    try:
        if args.output.exists():
            raise ValueError('Output already exists; choose a new evidence path.')
        result = inspect(args.release, args.namespace)
        with args.output.open('x') as stream:
            stream.write(json.dumps(result, indent=2) + '\n')
        print(json.dumps(result, indent=2))
        print('Saved inspection:', args.output)
    except (OSError, ValueError, KeyError, TypeError, subprocess.SubprocessError) as exc:
        parser.exit(1, 'Inspection failed: ' + str(exc) + '\n')


if __name__ == '__main__':
    main()
